exports.LOAN_STATUS = {
  REQUEST: "REQUEST",
  REJECT: "REJECT",
  CANCLE: "CANCLE",
  FUNDRAISING: "FUNDRAISING",
  PAYING: "PAYING",
  DONE: "DONE",
};

exports.LOAN_SCHEDULE_STATUS = {
  PAYING: "PAYING",
  PAID: "PAID",
};

exports.LOAN_SCHEDULE_TYPE = {
  FIXED_PAYMENT: "FIXED_PAYMENT",
  INTEREST_PAYMENT: "INTEREST_PAYMENT",
  PENALTY_PAYMENT: "PENALTY_PAYMENT",
};

exports.USER_TYPE = {
  STUDENT: "STUDENT",
  INVESTOR: "INVESTOR",
};

exports.USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DISABLED : "DISABLED"
};
exports.ACCOUNT_TYPE = {
  LOAN_ACCOUNT: "LOAN_ACCOUNT",
};
exports.ACCOUNT_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};
exports.TRANSACTION_STATUS = {
  COMPLETE: "COMPLETE",
  DELETED: "DELETED",
};
