exports.LOAN_STATUS = {
  DRAFT: "DRAFT",
  DELETED : "DELETED",
  WAITING : "WAITING",
  REJECTED : "REJECTED",
  FUNDING : "FUNDING",
  FAIL : "FAIL",
  ONGOING : "ONGOING",
  FINISH : "FINISH"
};

exports.LOAN_SCHEDULE_STATUS = {
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
  INCOMPLETE : "INCOMPLETE"
};

exports.LOAN_SCHEDULE_TYPE = {
  STP : "STUDYING_PAID",
  GP : "GRADUATED_PAID"
};

exports.USER_TYPE = {
  STUDENT: "STUDENT",
  INVESTOR: "INVESTOR",
};

exports.USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  BAN : "BAN"
};
exports.ACCOUNT_TYPE = {
  LOAN_ACCOUNT: "LOAN_ACCOUNT",
};
exports.ACCOUNT_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};
exports.TRANSACTION_STATUS = {
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
};
exports.INVESTMENT_STATUS = {
  PENDING: "PENDING",
  CANCEL: "CANCEL",
  INVESTED: "INVESTED",
  FAIL: "FAIL",
};

exports.INVESTOR_STATUS = {
  VERIFIED: "VERIFIED",
  UNVERIFIED: "UNVERIFIED"
};

exports.STUDENT_STATUS = {
  VERIFIED: "VERIFIED",
  UNVERIFIED: "UNVERIFIED"
};

exports.ACHIEVEMENT_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE : "INACTIVE"
};

exports.LOANMEDIA_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE : "INACTIVE"
};

exports.TUTOR_STATUS = {
  VERIFIED: "VERIFIED",
  UNVERIFIED: "UNVERIFIED"
};

exports.SCHOOL_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE : "INACTIVE"
};
exports.MAJOR_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE : "INACTIVE"
};
exports.SCHOOLMAJOR_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE : "INACTIVE"
};

exports.REPORT_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE : "INACTIVE"
};